
dataset_create:
    path:     /create
    controller: App\Controller\DataSetController::create
    methods:  [GET,POST]

dataset_edit:
    path:     /{id}/edit
    controller: App\Controller\DataSetController::edit
    methods:  [GET,POST]

